blog/apps/noticias/urls.py
from django.urls import path
from apps.noticias import views

urlpatterns = [

    path(route='',view=views.Listar_Noticias.as_view(), name = 'blog'),
        #view=views.PostsFeedView.as_view(),
        
    path(route='Detalle/<int:pk>',view=views.Detalle_Noticia.as_view(), name = 'detail'),
        #view=views.PostDetailView.as_view(),

    path(route='posts/save_coment', view=views.Comentar_Noticia, name='save_coment' ),
]

blog/apps/usuarios/urls.py
"""Users URLs."""

# Django
from django.urls import path
from django.views.generic import TemplateView
# View
from apps.usuarios import views

urlpatterns = [
    path(
        route='login',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='registro',
        view=views.RegistroForm.as_view(),
        name='registro'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='registro_completado/',
        view=TemplateView.as_view(template_name='usuarios/registrok.html'),
        name='registrok'
    ),
]

blog/blog/urls.py
"""blog URL Configuration """

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
        
    path('', include(('apps.noticias.urls', 'noticias'), namespace='posts')),

    path(route='about',view=TemplateView.as_view(template_name='about.html'), name='about'),

    path('', include(('apps.usuarios.urls', 'usuarios'), namespace='users')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block title %}Sobre Nosotros{% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h1 class="mt-4">Grupo: Los Discipulos de Adrian y Pablo</h1>
        <hr>
        <img class="img-fluid rounded" src="https://gcdn.emol.cl/artes-marciales/files/2018/07/Ninja.jpg" alt="">
        <hr>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>
        <hr>
      </div>
{% endblock %}

blog/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	{# Load CSS and JavaScript #}
	{% bootstrap_css %}
	{% bootstrap_javascript %}
	{# Display django.contrib.messages as Bootstrap alerts #}
	{% bootstrap_messages %}
    <title>Proyecto-Final</title>
	<link rel="stylesheet" href="{% static 'css/blog-home.css' %}">
</head>
<body>
	<!-- Navigation -->
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container-fluid">
			  <a class="navbar-brand" href="#"><img class="logo" src="{% static 'img/logo.png' %}" alt="logo" width="50px" heigth="50px"></a>
			  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			  </button>
			  <div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				  <li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url 'posts:blog' %}">Home</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'about' %}">Nosotros</a>
				  </li>
				  {% if user.is_authenticated %}
				  <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						Hola, {{request.user.username}}
					</a>
						<div class="dropdown-menu">
						   <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
						</div>
					 </li>
					 {% else %}
					  <li><a class="nav-link"  href="{% url 'users:login' %}">Login</a></li>
					  <li><a class="nav-link" href="{% url 'users:registro' %}">Registro</a></li>
					
					{% endif %}
				  </li>
				  <li class="nav-item">
					<a class="nav-link disabled">Disabled</a>
				  </li>
				</ul>
				<form class="d-flex">
				  <input class="form-control me-2" type="search" placeholder="buscar noticia" aria-label="Search">
				  <button class="btn btn-outline-success" type="submit">Buscar</button>
				</form>
			  </div>
			</div>
		  </nav>
		
				
	 <!-- Page Content -->
	 <div class="container">
		
		{% block content %}{% endblock %} 
	   <!-- Sidebar Widgets Column -->
	   <div class="col-md-4">
		  <!-- Categories Widget -->
		  <div class="card my-4">
			 <h5 class="card-header">Categorias</h5>
			 <div class="card-body">
				<div class="row">
				   <div class="col-lg-12">
					  <ul class="list-unstyled mb-0">
						{% for categ in categorias %}
						<li>
							<a href="#">{{categ.nombre}}</a>
						</li>
						{% endfor %}
					  </ul>
				   </div>
				</div>
			 </div>
		  </div>
		  <!-- Side Widget -->
		  <div class="card my-4">
			 <h5 class="card-header">Side Widget</h5>
			 <div class="card-body">
				You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
			 </div>
		  </div>
	   </div>
	</div>
	<!-- Footer -->
	<footer class="py-5 bg-dark">
	   <div class="container">
			
		  <p class="m-0 text-center text-white">Copyright &copy; 2023 Blog: Los discipulos de Adrian y Pablo {% now "Y" %}</p>
	   </div>
	   <!-- /.container -->
	</footer>
 </body>
</html>

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}HOME{% endblock titulo %}


{% block contenido %}
	<h2>HOLA SOY EL HOME</h2>
{% endblock contenido %}