blog/apps/noticias/urls.py
from django.urls import path
from apps.noticias import views

urlpatterns = [

    path(route='',view=views.Listar_Noticias.as_view(), name = 'blog'),
        #view=views.PostsFeedView.as_view(),
        
    path(route='Detalle/<int:pk>',view=views.Detalle_Noticia.as_view(), name = 'detail'),
        #view=views.PostDetailView.as_view(),

    path(route='posts/save_coment', view=views.Comentar_Noticia, name='save_coment' ),
]

blog/blog/urls.py
"""blog URL Configuration """

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
        
    path('', include(('apps.noticias.urls', 'noticias'), namespace='posts')),

    path(route='about',view=TemplateView.as_view(template_name='about.html'), name='about'),

    path('', include(('apps.usuarios.urls', 'usuarios'), namespace='users')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/noticias/models.py
"""Noticias models."""

from django.db import models
from ckeditor.fields import RichTextField

from apps.usuarios.models import Usuario
from apps.categorias.models import Categoria

class Noticia(models.Model):
	user = models.ForeignKey( Usuario, on_delete = models.PROTECT )
	titulo = models.CharField(max_length=255, null=False)
	subtitulo = models.CharField(max_length=255, null=True, blank=True)
	imagen = models.ImageField(null=True, blank=True, upload_to = 'noticias', default='static/post-default.png')
	texto = RichTextField(null=False)
	fecha_creacion = models.DateTimeField(auto_now_add=True)
	fecha_modificacion = models.DateTimeField(auto_now=True)
	activo = models.BooleanField(default=True)
	categoria_noticia = models.ManyToManyField(Categoria, null=True, default='Sin Categoria')
        
	class Meta:
		ordering = ('titulo',)
    
	def __str__(self):
		return '{} por @{}'.format(self.titulo, self.user.username)
	def save(self, *args, **kwargs):
		super().save(*args,**kwargs)

blog/apps/noticias/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from apps.noticias.models import Noticia
from apps.comentarios.models import Comentario
from apps.categorias.models import Categoria
# Forms
#from apps.comentarios.forms import Crear
from django.urls import reverse_lazy

# Forms
from apps.comentarios.forms import CrearFormComentario


class Listar_Noticias(ListView):
    """List."""
    template_name = 'noticias/index.html'
    model = Noticia
    ordering = ('-titulo',)
    paginate_by = 10
    context_object_name = 'posts'
    #para añadir condiciones opcionals
	#queryset = Post.objects.filter(activo=False)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cat = Categoria.objects.all().order_by('nombre')
        context['categorias'] = cat
        return context

class Detalle_Noticia(DetailView):
    """Detail """
    template_name = 'noticias/detail.html'
    model = Noticia
    context_object_name = 'post'

    
    # def get_queryset(self):
    #return Noticia.objects.filter(Categoria=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all()
        context['comentarios'] = Comentario.objects.filter(post=self.get_object()).all()
        context['form_coments'] = CrearFormComentario()
        return context


@login_required
def Comentar_Noticia(request):
    if request.method == 'POST':
        post = {
            'user': request.user.id,
            'comentario': request.POST['coment'],
            'post': request.POST['post']
        }
        form = CrearFormComentario(post)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('posts:detail', kwargs={'pk': post}))
    else:
        return HttpResponse(status=405)
    return HttpResponse(status=500)

blog/templates/noticias/detail.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h1 class="mt-4">{{post.titulo}}</h1>
        <p class="lead">
          por 
          <a href="#">{{post.user.username}}</a>
        </p>
        <hr>
        <p>Escrito el {{post.fecha_creacion}}</p>
        <hr>
        <img class="img-fluid rounded" src="{{ post.imagen.url }}" alt="">
        <hr>
        <p class="lead">{{post.texto|safe}}</p>
        <hr>
        {% if post.user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Deja un comentario:</h5>
          <div class="card-body">
            <form method="POST" action="{% url "posts:save_coment" %}">
              {% csrf_token %}
              <input type="hidden" name="post" value="{{post.id}}" />
              <div class="form-group">
                <textarea class="form-control" name="coment" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Enviar</button>
            </form>
          </div>
        </div>
        {% endif %}
        {% for coment in comentarios %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{coment.user.username}}</h5>
            {{coment.comentario}}
          </div>
        </div>
        {% endfor %}
      </div>
{% endblock %}

blog/templates/noticias/index.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
      <div class="col-md-8">

        <h1 class="title1 my-4">Listado de Noticias</h1>
        {% for post in posts %}
        <div class="card mb-4">
          <a href="#!"><img class="card-img-top" src="{{post.imagen.url}}" alt="..." /></a>
          <div class="card-body">
              <div class="small text-muted">{{post.fecha_creacion}}</div>
              <h2 class="card-title">{{post.titulo}}</h2>
              <p class="card-text">{{post.texto|safe|truncatechars:300}}</p>
              <a href="{% url 'posts:detail' post.pk %}" class="btn btn-primary">Leer más &rarr;</a>
          </div>
          <div class="card-footer text-muted">
            Escrito el {{post.fecha_creacion}} por
            <a href="#">{{post.user.username}}</a>
          </div>
        </div>
        {% endfor %}
        <ul class="pagination justify-content-center mb-4">
          <li class="page-item">
            <a class="page-link" href="#">&larr; Anterior</a>
          </li>
          <li class="page-item disabled">
            <a class="page-link" href="#">Siguiente &rarr;</a>
          </li>
        </ul>
      </div>
{% endblock %}