blog/apps/usuarios/urls.py
"""Users URLs."""

# Django
from django.urls import path
from django.views.generic import TemplateView
# View
from apps.usuarios import views

urlpatterns = [
    path(
        route='login',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='registro',
        view=views.RegistroForm.as_view(),
        name='registro'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='registro_completado/',
        view=TemplateView.as_view(template_name='usuarios/registrok.html'),
        name='registrok'
    ),
]

blog/blog/urls.py
"""blog URL Configuration """

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
        
    path('', include(('apps.noticias.urls', 'noticias'), namespace='posts')),

    path(route='about',view=TemplateView.as_view(template_name='about.html'), name='about'),

    path('', include(('apps.usuarios.urls', 'usuarios'), namespace='users')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/usuarios/models.py
""" Users models."""

from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    is_medical = models.BooleanField(default=False)
    is_physiotherapist = models.BooleanField(default=False)
    is_patient = models.BooleanField(default=False)

    class Meta:
        db_table = 'auth_user'

class AdminProfile(models.Model):
    user = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    photo = models.ImageField(upload_to='media',blank=True,null=True, default="media/admin-default.png")
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Administrador'
        verbose_name_plural = 'Administradores'

    def __str__(self):
        """Return username."""
        return self.user.username


class ColaboradorProfile(models.Model):
    user = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    photo = models.ImageField(upload_to='media',blank=True,null=True, default="media/colaborador-default.png")
    date_modified = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = 'Colaborador'
        verbose_name_plural = 'Colaboradores'

    def __str__(self):
        """Return username."""
        return self.user.username


class VisitanteProfile(models.Model):
    user = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='media',blank=True,null=True, default="media/visitante-default.png")
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Visitante'
        verbose_name_plural = 'Visitantes'

    def __str__(self):
        """Return username."""
        return self.user.username

blog/apps/usuarios/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
# Models
from django.contrib.auth.models import User
from apps.usuarios.models import AdminProfile

class RegistroForm(forms.Form):
    """Sign up form."""

    email = forms.CharField(min_length=6,max_length=70,widget=forms.EmailInput())
    username = forms.CharField(min_length=6,max_length=70,widget=forms.TextInput())
    password = forms.CharField(max_length=70,widget=forms.PasswordInput())
    password_confirmation = forms.CharField(max_length=70,widget=forms.PasswordInput())

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Las contraseñas no coinciden.')
        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')
        user = User.objects.create_user(**data)

        ## aca se debe agregar perfil
        profile = AdminProfile(user=user)
        profile.save()

blog/apps/usuarios/views.py
from django.shortcuts import render
from django.views.generic import FormView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views

from apps.usuarios.forms import RegistroForm
# Create your views here.

class RegistroForm(FormView):
	#FORMULARIO DJANGO
	form_class = RegistroForm
	success_url = reverse_lazy('users:registrok')
	template_name = 'usuarios/registro.html'
	
	def form_valid(self, form):
		form.save()
		return super().form_valid(form)

class LoginView(auth_views.LoginView):
    """Login view."""
    template_name = 'usuarios/login.html'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""
    template_name = 'usuarios/logged_out.html'

blog/templates/usuarios/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load django_bootstrap5 %}

    {% bootstrap_css %}

    {% bootstrap_javascript %}

    {% bootstrap_messages %}
    <title>Proyecto-Final - Login</title>
    
	<link rel="stylesheet" type="text/css" href="{% static 'css/signin.css' %}">
</head>
<body>
    {% block content %}

    {% endblock content %}
    
  
           <p class="m-0 text-center">Copyright &copy; 2023 Blog: Los discipulos de Adrian y Pablo {% now "Y" %}</p>
        
  </body>
 </html>

blog/templates/usuarios/login.html
{% extends 'usuarios/base.html' %}
{% block content %}
<form method="POST" action="{% url "users:login" %}" class="form-signin">
    {% csrf_token %}
    <h1><a class="title-link">Blog</a></h1>
    <h1 class="h3 mb-3 font-weight-normal">Login</h1>
    <label for="id_username" class="sr-only">Usuario</label>
    <input type="text" id="id_username" class="form-control" placeholder="Usuario" name="username" required autofocus>
    <label for="id_password" class="sr-only">Contraseña</label>
    <input type="password" id="id_password" class="form-control" placeholder="Contraseña" name="password" required>
    <div class="checkbox mb-3"></div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    </form>
{% endblock %}

blog/templates/usuarios/registro.html
{% extends 'usuarios/base.html' %}
{% load static %}
{% block title %}Registro Usuario{% endblock %}
{% block content %}
<form class="form-signin" method="POST">
  {% csrf_token %}
  <h1><a href="#" class="title-link">Simple Blog</a></h1>
  <h1 class="h3 mb-3 font-weight-normal">Registro</h1>
  <label for="id_email" class="sr-only">Email</label>
    <input type="email" name="email" id="id_email" class="form-control" placeholder="Email" required autofocus>
    <label for="id_username" class="sr-only">Nombre de usuario</label>
    <input type="text" name="username" id="id_username" class="form-control" placeholder="Nombre de usuario" required>
    <label for="inputPassword" class="sr-only">Contraseña</label>
    <input type="password" name="password" id="id_password" class="form-control" placeholder="Contraseña" required>
    <label for="inputPassword" class="sr-only">Repetir contraseña</label>
    <input type="password" name="password_confirmation" id="id_password_confirmation" class="form-control" placeholder="Repetir contraseña" required>
    <div class="checkbox mb-3"></div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Registrarse</button>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    
    </form>
{% endblock %}

blog/templates/usuarios/registrok.html
{% extends 'usuarios/base.html' %}
{% block title %}Registro completado{% endblock %}
{% block content %}
<main role="main" class="container">
   <div class="starter-template">
      <h1>Tu usuario ha sido creado con exito</h1>
      <p class="lead">Si la página no es redirigida en 5 segundos pulsa <a href="{% url 'users:login' %}">aquí</a></p>
   </div>
</main>
<script>
   setTimeout(function(){ 
       window.location.replace("{% url 'users:login' %}");
   }, 5000);
</script>
{% endblock %}